title: Farid Rashidi
description1: PhD Student at Indiana University (IU)
description2: PhD Student at Indiana University (IU)
twitter_username: farid_rashidi
github_username:  faridrashidi
linkedin_username: faridrashidi
scholar_username: ed4YbAIAAAAJ
comments: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# URL settings
url: "https://faridrashidi.github.io/"
baseurl: ""
permalink: /:title/

# Integrations
disqus_short_name: faridrashidi
disqus_show_comment_count: true
google_analytics_tracking_id: UA-122994885-1
