title: Farid Rashidi
description1: Predoctoral fellow, National Cancer Institute
description2: Ph.D. student, Indiana University Bloomington
twitter_username: farid_rashidi
github_username: faridrashidi
youtube_username: faridrsh
linkedin_username: faridrashidi
scholar_username: ed4YbAIAAAAJ
comments: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# URL settings
url: "https://farid.one"
baseurl: ""
permalink: /:title/

# Integrations
disqus_short_name: faridrashidi
disqus_show_comment_count: true
google_analytics_tracking_id: UA-122994885-1
