last_updated: February 23, 2022
title: Farid Rashidi
twitter_username: farid_rashidi
github_username: faridrashidi
youtube_username: faridrsh
linkedin_username: faridrashidi
orcid_username: 0000-0003-4103-4904
scholar_username: ed4YbAIAAAAJ
comments: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

url: "https://farid.one"
baseurl: ""
permalink: /:title/

disqus_short_name: faridrashidi
disqus_show_comment_count: true
google_analytics_tracking_id: UA-122994885-1
