title: Farid Rashidi
title-full: Farid Rashidi Mehrabadi
bio: Computational Oncologist and Data Scientist
description: Farid Rashidi | فرید رشیدی
external-image: true
picture: https://www.gravatar.com/avatar/42125cfaaf0a859652acd4832533745d?s=512
dark-theme: auto
url: "https://farid.one"
permalink: /:title/
analytics-google: UA-122994885-1

twitter: farid_rashidi
github: faridrashidi
# youtube: faridrsh
linkedin: faridrashidi
# orcid: 0000-0003-4103-4904
scholar: ed4YbAIAAAAJ
# facebook: farid.rashidi
# instagram: farid.rashidi
# email: myemail@gmail.com

publications: true
software: true

width: large
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
